# Global Config
language: python
sudo: required

services:
  - postgresql

addons:
  postgresql: "9.6"
  apt:
    packages:
      - postgresql-server-dev-9.6

before_script:
  - make
  - make install

script:
  - make installcheck
