# Global Config
language: python
sudo: required

services:
  - postgresql

addons:
  postgresql: "9.6"
  apt:
    packages:
      - postgresql-server-dev-9.6

script:
  - sudo make installcheck PGHOST=localhost PGUSER=postgres

# pg_regress only prints to files, so we need to print out contents on failure
after_failure:
  - cat $TRAVIS_BUILD_DIR/regression.diffs
