# Global Config
language: python
sudo: required

services:
  - docker

install:
  - sudo docker-compose build

script:
  - sudo docker-compose run --rm postgresql make installcheck PGHOST=postgresql PGUSER=postgres
