#
# Sets up development services
#
version: "3.0"
services:
  postgres:
    # Don't use alpine because we need diffutils
    build: .
    restart: always
    tmpfs: /var/lib/postgresql/data/
    ports:
      - "5432:5432"
    volumes:
      - ./regression:/usr/local/src/regression
