#
# Sets up development services
#
version: "3.0"
services:
  postgresql:
    # Don't use alpine because we need diffutils
    build: .
    restart: always
    tmpfs: /var/lib/postgresql/data/
    expose:
      - "5432"
    volumes:
      - .:/usr/local/src
