#
# Sets up development services
#
version: "3.0"
services:
  postgresql:
    build: .
    restart: always
    ports:
      - "5432:5432"
    tmpfs: /var/lib/postgresql/data
    volumes:
      - .:/usr/local/src
