#
# Sets up development services
#
version: "3.0"
services:
  postgresql:
    build: .
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - .:/usr/local/src
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
